apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: securepod
  name: securepod
  namespace: ashu
spec:
  imagePullSecrets:
   - name: ashusec
  containers:
  - image: ashutoshh.azurecr.io/ckad:v2
    name: securepod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
