apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sidecarpod
  name: sidecarpod
spec:
  volumes:
   - name: ashuvol
     emptyDir: {}
  containers:
  - image: nginx
    name: mainc1  #  main container
    ports:
     - containerPort: 80
    volumeMounts: 
     - name: ashuvol
       mountPath: /usr/share/nginx/html/

  - image: alpine
    name: mainc2  # sidecar 
    volumeMounts:
     - name: ashuvol
       mountPath: /random
    command:  ["/bin/sh","-c"," while true ; do echo  '<h1> Hello all i Am SideCar </h1>'   >>/random/index.html; sleep 5; done"]

    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
